# Zeebe standalone gateway configuration file, for the configuration of the embedded gateway
# see the gateway section of the zeebe.cfg.toml

# Overview -------------------------------------------

# This file contains a complete list of available configuration options.

# Default values:
#
# When the default value is used for a configuration option, the option is
# commented out. You can learn the default value from this file

# Conventions:
#
# Byte sizes
# For buffers and others must be specified as strings and follow the following
# format: "10U" where U (unit) must be replaced with K = Kilobytes, M = Megabytes or G = Gigabytes.
# If unit is omitted then the default unit is simply bytes.
# Example:
# sendBufferSize = "16M" (creates a buffer of 16 Megabytes)
#
# Time units
# Timeouts, intervals, and the likes, must be specified as strings and follow the following
# format: "VU", where:
#   - V is a numerical value (e.g. 1, 1.2, 3.56, etc.)
#   - U is the unit, one of: ms = Millis, s = Seconds, m = Minutes, or h = Hours
#
# Paths:
# Relative paths are resolved relative to the installation directory of the
# broker.

# ----------------------------------------------------

[network]
# Sets the host the gateway binds to
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_HOST.
# host = "0.0.0.0"
#
# Sets the port the gateway binds to
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_PORT.
# port = 26500

[cluster]
# Sets the broker the gateway should initial contact
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_CONTACT_POINT.
# contactPoint = "127.0.0.1:26502"

# Sets size of the transport buffer to send and received messages between gateway and broker cluster
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_TRANSPORT_BUFFER.
# transportBuffer = "2M"

# Sets the timeout of requests send to the broker cluster
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_REQUEST_TIMEOUT.
# requestTimeout = "15s"

# Sets name of the Zeebe cluster to connect to
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_CLUSTER_NAME.
# clusterName = "zeebe-cluster"

# Sets the member id of the gateway in the cluster
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_CLUSTER_MEMBER_ID.
# memberId = "gateway"

# Sets the host the gateway node binds to for internal cluster communication
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_CLUSTER_HOST.
# host = "0.0.0.0"

# Sets the port the gateway node binds to for internal cluster communication
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_CLUSTER_PORT.
# port = 26502

[threads]
# Sets the number of threads the gateway will use to communicate with the broker cluster
# This setting can also be overridden using the environment variable ZEEBE_GATEWAY_MANAGEMENT_THREADS.
# managementThreads = 1

[monitoring]
# Enables the metrics collection and exporting it over HTTP
# enabled = false
#
# Sets the host the monitoring binds to
# host = "0.0.0.0"
#
# Sets the port the monitoring binds to
# port = 9600